### ISSUE TITLE
Homebridge crashes if device is unreachable

### ISSUE THREAD

**Issue by jacopofranza** [lucavb/homebridge-esphome-ts#7] opened 2020-06-15 11:01 UTC
I've noticed that if one device running ESPhome is unreachable, maybe because is not power on, Homebridge won't start getting "Got SIGTERM, shutting down Homebridge...".
No error are present in log but with some tests I can confirm that the problem is for this reason.

**Comment by lucavb** [comment] 2020-06-15 20:39
Hey, 

yes, I can confirm that there is an issue in the underlying esphome client implementation when the device is not reachable. Thank you for reporting this issue. I am working on a fix, but since it is getting kinda late here, I will finish the work tomorrow.

**Comment by lucavb** [comment] 2020-06-16 18:33
Alright, so this should now be fixed with version 1.0.1.

**Comment by jacopofranza** [comment] 2020-06-16 18:45
Thanks Luca, I can confirm that there are no more crashes for unreachable devices, but the plugin seems not to log anything.

**Comment by lucavb** [comment] 2020-06-16 18:55
You should receive `[esphome] The device under the host my_esp.local could not be reached.` after about 10s.

**Closed** 2020-07-11 13:05 UTC
