### ISSUE TITLE
Only motion-sensor showing

### ISSUE THREAD

**Issue by tohusebo** [lucavb/homebridge-esphome-ts#1] opened 2020-04-13 15:53 UTC
Hi! 
Have installed the plugin, but only the motion sensor from my esphome is showing. 

<img width="602" alt="PNG-bilde" src="https://user-images.githubusercontent.com/16785804/79135502-accbaf00-7daf-11ea-854a-8480db0db471.png">

**Comment by lucavb** [comment] 2020-04-13 15:57
Would you mind telling me which accessory is missing? Could you share your esp config?

**Comment by tohusebo** [comment] 2020-04-13 16:08
I am using the "BRUH multisensor" https://esphome.io/cookbook/bruh.html
Have it set up and working fine in Home Assistant. 

I am missing temperature and humidity.

This is the config file:
`esphome:
  name: <NODE_NAME>
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: <SSID>
  password: <PASSWORD>

api:

# Enable logging
logger:

ota:

sensor:
  - platform: dht
    pin: D7
    temperature:
      name: "Multisensor Temperature"
    humidity:
      name: "Multisensor Humidity"
  - platform: adc
    pin: A0
    name: "Multisensor Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Multisensor Motion"
    device_class: motion

output:
  - platform: esp8266_pwm
    pin: D1
    id: redgpio
  - platform: esp8266_pwm
    pin: D2
    id: greengpio
  - platform: esp8266_pwm
    pin: D3
    id: bluegpio

light:
  - platform: rgb
    name: "Multisensor Light"
    red: redgpio
    green: greengpio
    blue: bluegpio`

**Comment by lucavb** [comment] 2020-04-13 16:51
Unfortunately I am not really able to reproduce this. It just flashed pretty much the exact same config onto mine and it discovers even the LED. Which version are you on? I the sensor support came in beta3. Did you do anything special?

**Comment by lucavb** [comment] 2020-04-13 16:53
Or maybe I messed up with releasing and it yet again didn't build a new dist folder 🙄

**Comment by tohusebo** [comment] 2020-04-13 20:25
Hmm. I am having trouble finding the directories you are mentioning... Am now on the new beta4. 
Running Homebridge from the prebuilt image for a Raspberry Pi 3. Could you point me in the right direction?

**Comment by lucavb** [comment] 2020-04-18 16:48
Okay please run the following

```
npm r -g homebridge-esphome-ts
npm i -g git://github.com/lucavb/homebridge-esphome-ts#debug-mode
```

This will install this project directly from GitHub with that debug version I just committed. The output of the second command should look like this 

```
> protobufjs@6.8.9 postinstall /usr/local/lib/node_modules/homebridge-esphome-ts/node_modules/protobufjs
> node scripts/postinstall

+ homebridge-esphome-ts@1.0.0-beta.4
added 63 packages from 83 contributors in 25.557s
```

Afterwards just add a debug key to your config and restart homebridge. It should now output what your ESP has communicated. Maybe this will tell us something.
```
"platform": "esphome",
"devices": [
    {
         "host": "10.0.0.128"
     }
],
"debug": true
```

**Comment by lucavb** [comment] 2020-05-20 19:28
Closed due to inactivity.

**Closed by lucavb** 2020-05-20 19:28 UTC
